# Generated by Django 5.1.7 on 2025-03-24 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swapfood', '0002_foodimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodimage',
            name='image_data',
        ),
        migrations.AddField(
            model_name='foodimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='food_images/'),
        ),
    ]
